export const constants = {
  returnWindow: "PT1H",
  timeToShip:"PT45M",
  customerCare:"Ramesh,ramesh@abc.com,18004254444",
  productUnit:["gram"],
  // productUnit:["unit","dozen","gram","kilogram","tonne","litre","millilitre"],
  dimensionUnit:["centimeter"],
  // dimensionUnit:["centimeter","meter"],
  servicibilityUnit:"km",
};

export const CgTags={
  code0:'type',
  list0code:'type',
  list0value:'custom_group',
  code1:'config',
  list1code:'min',
  list1value:'1',
  list2code: "max",
  list2value: "1",
  list3code: "input",
  list3value: "select",
  list4code: "seq",
  list4value: "1"
}

export const RProduct={
  quantityMeasureUnit:"unit",
  quantityMeasureValue:"1",
  availableCount:"99",
  maximumCount:"99",
  priceCurrency:"INR",
  priceMaximumValue:"0.0",
  categoryId:"F&B",
  related:true,
  code0:"type",
  listCode0:"type",
  listValue0:'customization',
  code1:"parent",
  listCode1:"id",
  listCode2:"default",
  listValue2:"yes",
  code2:"child",
  listCode3:"id",
  listValue3:"",
  code4:"veg_nonveg",
  listCode4:"veg",
  PriceTagsCode:"range",
  PriceTagsListCode:"lower",
  PriceTagsListValue:"269.0",
  PriceTagsListCode1:"upper",
  PriceTagsListValue1:"894.0",
  CategoryId:"F&B",
  recommended:true,
  tagsCode:"type",
  tagsListCode0:"type",
  tagsListValue0:"item",
  tagsCode1:"custom_group",
  tagsCode2:"timing",
  tagsList2Code1:"day_from",
  tagsList2Code2:"day_to",
  tagsList2Code3:"time_from",
  tagsList2Code4:"time_to",
  tagsCode3:"veg_nonveg",
  tagsList3code:"veg",
}

export const KProduct={
  parentItemId:"V1",
  quantityMeasureUnit:"kilogram",
  quantityMeasureValue:"1",
  availableCount:"99",
  maximumCount:"99",
  priceCurrency:"INR",
  priceMaximumValue:"0.0",
  categoryId:"F&B",
  related:true,
  code0:"type",
  listCode0:"type",
  listValue0:'customization',
  code1:"parent",
  listCode1:"id",
  listCode2:"default",
  listValue2:"yes",
  code2:"child",
  listCode3:"id",
  listValue3:"",
  code4:"veg_nonveg",
  listCode4:"veg",
  PriceTagsCode:"range",
  PriceTagsListCode:"lower",
  PriceTagsListValue:"269.0",
  PriceTagsListCode1:"upper",
  PriceTagsListValue1:"894.0",
  CategoryId:"F&B",
  recommended:true,
  tagsCode:"origin",
  tagsListCode0:"country",
  tagsListValue0:"IND",
  tagsCode1:"veg_nonveg",
  tagsList1code:"veg",
}